"""Add created_at and updated_at to User

Revision ID: 8ac1229f6113
Revises: 57cd892b9447
Create Date: 2021-09-07 13:00:38.119920

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8ac1229f6113"
down_revision = "57cd892b9447"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users__users",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "users__users",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users__users", "updated_at")
    op.drop_column("users__users", "created_at")
    # ### end Alembic commands ###
