"""Add manga likes

Revision ID: 128fdbf432b6
Revises: a3bab1ce971e
Create Date: 2021-08-31 19:03:36.588318

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "128fdbf432b6"
down_revision = "a3bab1ce971e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manga__manga_likes",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("manga_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["manga_id"],
            ["manga__manga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users__users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "manga_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manga__manga_likes")
    # ### end Alembic commands ###
