"""Add Authors and author-manga relationship

Revision ID: 57cd892b9447
Revises: 128fdbf432b6
Create Date: 2021-09-04 03:50:57.308890

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "57cd892b9447"
down_revision = "128fdbf432b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manga__author",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manga__manga_authors",
        sa.Column("author_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("manga_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "type",
            sa.Enum("writer", "artist", name="authorrelationshiptype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["manga__author.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manga_id"],
            ["manga__manga.id"],
        ),
        sa.PrimaryKeyConstraint("author_id", "manga_id", "type"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manga__manga_authors")
    op.drop_table("manga__author")
    op.execute("drop type authorrelationshiptype")
    # ### end Alembic commands ###
