"""Create MangaInfo

Revision ID: 771e34c5502b
Revises: 17508a7eb269
Create Date: 2021-08-22 11:30:06.400903

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "771e34c5502b"
down_revision = "17508a7eb269"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manga__manga_info",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("lang", sa.String(length=5), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2047), nullable=True),
        sa.Column("manga_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["manga_id"],
            ["manga__manga.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manga__manga_info")
    # ### end Alembic commands ###
