"""empty message

Revision ID: deec5fb628c9
Revises: aecd4516c41f
Create Date: 2021-08-22 13:04:34.097652

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "deec5fb628c9"
down_revision = "aecd4516c41f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("manga__manga", "title", nullable=False, type_=sa.String(length=255))
    op.add_column(
        "manga__manga", sa.Column("title_slug", sa.String(length=255), nullable=False)
    )
    op.create_unique_constraint("uq_title_slug", "manga__manga", ["title_slug"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_title_slug", "manga__manga", type_="unique")
    op.drop_column("manga__manga", "title_slug")
    op.alter_column("manga__manga", "title", nullable=False, type_=sa.String)
    # ### end Alembic commands ###
