"""Make username unique

Revision ID: aecd4516c41f
Revises: a2f3c00ada16
Create Date: 2021-08-22 11:33:59.210238

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "aecd4516c41f"
down_revision = "a2f3c00ada16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users__users", ["username"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users__users", type_="unique")
    # ### end Alembic commands ###
