"""Create MangaArt

Revision ID: c2587dc7c10f
Revises: 771e34c5502b
Create Date: 2021-08-22 11:31:04.965935

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c2587dc7c10f"
down_revision = "771e34c5502b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manga__manga_art",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("manga_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["manga_id"],
            ["manga__manga.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manga__manga_art")
    # ### end Alembic commands ###
