"""Make manga info language length 2

Revision ID: 8eec50ffdd33
Revises: 1694021b577f
Create Date: 2021-08-27 09:22:42.036004

"""
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy import String

revision = "8eec50ffdd33"
down_revision = "1694021b577f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("manga__manga_info", "lang", nullable=False, type_=String(2))
    # ### end Alembic commands ###


def downgrade():
    op.alter_column("manga__manga_info", "lang", nullable=False, type_=String(5))
